version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - .:/app
  db:
    image: mysql:latest # use latest version of mysql
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: pablodev
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: database_bhub # create this database on startup
    ports:
      - '3306:3306'
   
    